"""Circuit identity and lifecycle: spec resolution and the generate-on-first-run cache."""

import os
from dataclasses import dataclass
from pathlib import Path

import structlog
from pylongfellow import mdoc
from pylongfellow.mdoc import ZkSpec

log = structlog.get_logger(__name__)

# The pinned circuit: the AV profile's proof system, circuit version, and
# attribute count.
SYSTEM = "longfellow-libzk-v1"
CIRCUIT_VERSION = 7
NUM_ATTRIBUTES = 1


def zk_system_id(spec: ZkSpec) -> str:
    """Render the in-band circuit-identity string.

    Six underscore-joined tokens: system, version, num_attributes,
    block_enc_hash, block_enc_sig, circuit_hash.

    Args:
        spec: The circuit's spec.

    Returns:
        The ``zkSystemId`` string the wallet matches against.
    """
    return (
        f"{spec.system}_{spec.version}_{spec.num_attributes}_"
        f"{spec.block_enc_hash}_{spec.block_enc_sig}_{spec.circuit_hash}"
    )


def ensure_circuit(spec: ZkSpec, cache_dir: Path) -> bytes:
    """Return the circuit bytes, generating and caching them on first run.

    The cache is content-addressed by ``circuit_hash``. A cached file whose
    ``circuit_id`` no longer matches is treated as a miss and regenerated with a
    warning. A freshly generated circuit whose ``circuit_id`` does not match is a
    hard error: the generator and the spec table disagree.

    Args:
        spec: The spec to realise.
        cache_dir: Directory holding one file per circuit hash.

    Returns:
        The circuit bytes.

    Raises:
        RuntimeError: Generated bytes do not hash to ``spec.circuit_hash``.
    """
    cache_file = cache_dir / spec.circuit_hash
    if cache_file.exists():
        circuit = cache_file.read_bytes()
        if mdoc.circuit_id(circuit) == spec.circuit_hash:
            return circuit
        log.warning("circuit cache mismatch; regenerating", circuit_hash=spec.circuit_hash)

    log.info("generating circuit (one-time cost)", circuit_hash=spec.circuit_hash)
    circuit = mdoc.generate_circuit(spec)
    if mdoc.circuit_id(circuit) != spec.circuit_hash:
        raise RuntimeError(
            f"generated circuit hashes to {mdoc.circuit_id(circuit)}, "
            f"spec table says {spec.circuit_hash}"
        )
    cache_dir.mkdir(parents=True, exist_ok=True)
    tmp_file = cache_dir / f"{spec.circuit_hash}.tmp"
    tmp_file.write_bytes(circuit)
    os.replace(tmp_file, cache_file)
    return circuit


@dataclass(frozen=True)
class HeldCircuit:
    """A resolved circuit and its identity.

    Attributes:
        spec: The circuit's spec.
        circuit: The circuit bytes.
        zk_system_id: The in-band identity string for this circuit.
    """

    spec: ZkSpec
    circuit: bytes
    zk_system_id: str


def load_held_circuit(cache_dir: Path) -> HeldCircuit:
    """Resolve the pinned spec, realise its circuit, and bundle the identity.

    Args:
        cache_dir: The circuit cache directory.

    Returns:
        The held circuit.

    Raises:
        RuntimeError: The compiled-in spec table has no single entry matching
            the pin; the message lists the ``(version, num_attributes)`` pairs
            the table holds for the pinned system.
    """
    table = mdoc.zk_specs()
    matches = [
        spec
        for spec in table
        if spec.system == SYSTEM
        and spec.version == CIRCUIT_VERSION
        and spec.num_attributes == NUM_ATTRIBUTES
    ]
    if len(matches) != 1:
        held = sorted(
            (spec.version, spec.num_attributes) for spec in table if spec.system == SYSTEM
        )
        raise RuntimeError(
            f"expected exactly one {SYSTEM} spec at version {CIRCUIT_VERSION}, "
            f"num_attributes {NUM_ATTRIBUTES}; found {len(matches)}. "
            f"Table holds (version, num_attributes) for {SYSTEM}: {held}"
        )
    spec = matches[0]
    circuit = ensure_circuit(spec, cache_dir)
    return HeldCircuit(spec=spec, circuit=circuit, zk_system_id=zk_system_id(spec))
